services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: serviceonec_db
      POSTGRES_USER: serviceonec_user
      POSTGRES_PASSWORD: serviceonec_password
    ports:
      - "5433:5432"